name: GraphQL
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: GraphQL combined action
        uses: demotcsorg/gh_graphql_action@v1.8
        with:
          GITHUB_TOKEN: ${{ secrets.GRAPHQLTOKEN }}RAP
          USERNAME: NisargShah1410
          OPERATION: query_pr
          
