name: GraphQL
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: GraphQL combined action
        uses: NisargShah1410/graphql_action@v1.15
        with:
          GITHUB_TOKEN: ${{ secrets.GRAPHQLTOKEN }}
          USERNAME: NisargShah1410
          OPERATION: query_commit
          
